export const inputData = [
	{
		id: 'username',
		name: 'username',
		type: 'text',
		placeholder: 'Wprowadź swoje imię i nazwisko',
		label: 'Imię i nazwisko',
		errorMessage: 'Wprowadź poprawnie dane!',
		pattern: '^[A-Za-zżźćńółęąśŻŹĆĄŚĘŁÓŃ ]{3,32}$',
		required: true,
	},
	{
		id: 'email',
		name: 'email',
		type: 'email',
		placeholder: 'Wprowadź swój e-mail',
		label: 'E-mail',
		errorMessage: 'Wprowadź poprawnie e-mail!',
		required: true,
	},
	{
		id: 'phone',
		name: 'phone',
		type: 'tel',
		placeholder: 'Wprowadź numer telefonu',
		label: 'Nr telefonu',
		errorMessage: 'Wprowadź poprawnie nr telefonu!',
		pattern: '^[0123456789+]{9,12}$',
		required: true,
	},
];
