export { default as Footer } from './Footer';
export { default as Navbar } from './Navbar';
export { default as Offer } from './Offer';
export { default as OfferCategory } from './OfferCategory';
export { default as Prices } from './Prices';
export { default as Contact } from './Contact';
export { default as PageNotFound } from './PageNotFound';
export { default as PrivacyPolicy } from './PrivacyPolicy';
export { default as Home } from './Home';
